board/urls.py
from django.urls import path
from . import views 

app_name = 'board'
urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('create/', views.board_create, name='board_create'),
    path('create/form/', views.board_create_form, name='board_create_form'),
    path('form_submit/', views.form_submit, name='form_submit'),
    path('detail/<int:pk>/', views.board_detail, name='board_detail'),
    path('temp-upload/', views.temp_upload, name='temp_upload'),
    path('refresh_session/', views.refresh_session, name='refresh_session'),
    path('detail/<int:pk>/edit/', views.board_detail_edit, name='board_detail_edit'),
    path('delete/<int:pk>/', views.board_delete, name='board_delete'),
    path('update/<int:pk>/', views.board_update, name='board_update'),
    path('board_search/', views.board_search, name='board_search'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from config.views import HomeView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('roadmap/', include('roadmap.urls')),
    path('', HomeView.as_view(),name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/check/', views.check_profile, name='check_profile'),
    path('profile/create/step1/', views.profile_create_step1, name='profile_create_step1'),
    path('profile/create/step2/', views.profile_create_step2, name='profile_create_step2'),
    path('profile/create/step3/', views.profile_create_step3, name='profile_create_step3'),
    path('profile/create/step4/', views.profile_create_step4, name='profile_create_step4'),
    path('profile/complete/', views.profile_complete, name='profile_complete'),
    path('weekly_plan/', views.weekly_plan, name='weekly_plan'),
    path('api/get_nutrition/', views.get_nutrition, name='get_nutrition'),  # API 엔드포인트
]

board/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

class Post(models.Model):
    post_title = models.CharField(max_length=255)
    post_content = models.TextField()
    post_timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 문자열 기반 참조
    visitors = models.IntegerField(default=0)

    def __str__(self):
        return self.post_title

class PostImage(models.Model):
    image_url = models.ImageField(upload_to='post_images/', blank=True, null=True)
    image_order = models.IntegerField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

board/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # 실제 저장받는 필드
        fields = ['post_title', 'post_content']
        widgets = {
            'post_title': forms.TextInput(attrs={'placeholder': '포스트 제목...'}),
            'post_content': forms.Textarea(attrs={'placeholder': '내용 입력...'}),
            # 사용자에게 보이는 필드
        }
        labels = {
            'post_title': '',  
            'post_content': '',
        }


class PostSearchForm(forms.Form):
    search_word = forms.CharField(
        label= '',
        widget=forms.TextInput(attrs={
            'placeholder': '포스트 검색',
            'id': 'search-query'
            })
    )

        
        

board/views.py
from django.shortcuts import render, redirect
from .models import Post, PostImage
from .forms import PostForm, PostSearchForm
from django.http import JsonResponse
import os
import json
from django.utils import timezone
from io import BytesIO
from django.http import HttpResponse
from django.db.models import Q
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


User = get_user_model()



# Create your views here.
def board_list(request):
    post = Post.objects.all().order_by('-post_timestamp')  # 최신 포스트가 먼저 나오도록 정렬
    
    # 페이지네이션
    paginator = Paginator(post, 12)  # 한 페이지에 12개씩 보이도록 설정
    page_number = request.GET.get('page', 1)  # 기본적으로 첫 페이지를 설정
    page_obj = paginator.get_page(page_number)

    post_img = PostImage.objects.filter(image_order=0)
    search_form = PostSearchForm()
    user = request.user


    context = {
        'posts' : page_obj, # 페이지네이션 된 포스트
        'post_img': post_img,
        'search_form': search_form,
        'user':user,
        'paginator': paginator,
        'page_obj': page_obj,
    }

    return render(request, 'board/board_list.html', context)

@login_required
def board_create(request):
   
    return render(request, 'board/board_create.html')

def  board_create_form(request):
    user = request.user
    
    if request.method == 'POST':
        
        form = PostForm()
        uploaded_files = request.POST.get('uploadedFiles')

        if uploaded_files:
            uploaded_files = json.loads(uploaded_files)
            request.session['uploaded_files'] = uploaded_files

        return redirect('board:board_create_form')
    
    else:  # GET 요청 처리
        form = PostForm()

    context = {
        'form': form,
        'user':user,
    }
    return render(request, 'board/board_create_form.html', context)

# 게시하기 눌렀을 때 
def form_submit(request):
    if request.method == 'POST':
        # 폼 제출 시 Title / content / 전시 / user
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
             # request.user를 직접 사용하지 않고, User 모델 객체를 사용하여 처리
            try:
                user = User.objects.get(pk=request.user.pk)
                post.user = user
            except User.DoesNotExist:
                raise Exception('User 객체가 아닙니다.')

            post.post_timestamp = timezone.now()
            post.save()

            # 세션 / 서버 temp에서 파일 가져와야됨
            # 연결 hidden 으로 저장 시키든가 다른방법
            
            # 세션에서 업로드된 파일 정보 가져오기
            uploaded_files = request.session.get('uploaded_files', [])
            for index, file_info in enumerate(uploaded_files):
                if 'file_url' in file_info:
                    # 파일 절대 경로 구성
                    file_path = os.path.join(settings.TEMP_UPLOAD_DIR, file_info['filename'])
                    with open(file_path, 'rb') as file:
                        image = file.read()
                    
                    # 파일명에서 확장자 추출
                    _, ext = os.path.splitext(file_info['filename'])
                    ext = ext.lower()

                     # Django의 InMemoryUploadedFile으로 변환
                    memory_file = BytesIO(image)
                    memory_file.name = file_info['filename']
                    memory_file.seek(0)

                    post_img = PostImage.objects.create(
                        # image_url= image,
                        image_order=index,
                        post=post
                    )
                    
                    post_img.image_url.save(file_info['filename'], InMemoryUploadedFile(memory_file, None, file_info['filename'], 'image/%s' % ext.lower(), memory_file.tell, None))
                    
                    post_img.save()
                    
                    if os.path.exists(file_path):
                        os.remove(file_path)
                else:
                    # 'file_url' 키가 없을 경우 처리
                    print(f"'file_url'이 누락된 업로드 파일 정보: {file_info}")
              
        
            # 성공적으로 저장되었을 때 세션에서 업로드된 파일 데이터 삭제
            # del request.session['uploaded_files']
            print("세션에서 'uploaded_files' 삭제됨")
                # 현재 세션 데이터 출력 (디버깅용)
            print("현재 세션 데이터:", request.session.items())
            
            return JsonResponse({'status':'success', 'pk': post.id})
        else:
            # 폼이 유효하지 않은 경우 폼을 다시 렌더링하여 에러 메시지를 표시합니다.
            # return render(request, 'board/board_create_form.html', {'form': form})
        # 폼이 유효하지 않은 경우 JSON 응답을 반환
            errors = form.errors.as_json()
            return JsonResponse({'status': 'error', 'errors': errors}, status=400)

     # 유효하지 않은 폼 데이터가 있을 경우 다시 폼을 보여줌
    print("유효하지 않은 데이터")
    # return redirect('board:board_create_form')
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=400)

def board_detail(request, pk):
    post = Post.objects.get(pk=pk)
    post_img = PostImage.objects.filter(post=post)
    user = request.user
    post.visitors += 1
    post.save()
    
    context = {
        'post' : post,
        'post_img': post_img,
        'user': user,
    }
    return render(request, 'board/board_detail.html', context)

def temp_upload(request):
    # 브라우저에서 30초동안 신호를 받지 않을 때 서버 media폴더 tempd폴더에만 사진저장됨
    # 같은 유저인지 확인
    if request.method == 'POST':
        file = request.FILES['file']
        fs = FileSystemStorage(location=settings.TEMP_UPLOAD_DIR)
        filename = fs.save(file.name, file)
        file_url = fs.url(filename)

         # 세션에 업로드된 파일 정보 저장
        user = User.objects.get(pk=request.user.pk)
        uploaded_files = request.session.get('uploaded_files', [])
        
        uploaded_files.append({'file_url': file_url, 'filename': filename, 'user': user.username })
        request.session['uploaded_files'] = uploaded_files
        
        # 테스트용 세션데이터 많아짐 > 임시 전체장고세션 비우기
        # del request.session['uploaded_files']

        return JsonResponse({'file_url': file_url, 'filename': filename})
    return JsonResponse({'error': 'Invalid request'}, status=400)

# 세션 지우기
def refresh_session(request):
    if request.method == 'GET':
        # 세션에서 업로드된 파일 정보 가져오기
        del request.session['uploaded_files']
        return JsonResponse({'status': 'success'})
        
    return JsonResponse({'status': 'error'}, status=400)


def board_detail_edit(request,pk):
    post = Post.objects.get(pk=pk)
    post_img = PostImage.objects.filter(post=post)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid:
            form.save()
            return redirect('board:board_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    context = {
        'post': post,
        'form': form,
        'post_img': post_img,
    }

    return render(request,'board/board_detail_edit.html', context)

def board_delete(request, pk):
    if request.method=="POST":
        post = Post.objects.get(pk=pk)
        post.delete()

        return redirect('board:board_list')
    return HttpResponse(status=405)

def board_update(request, pk):
    if request.method=="POST":
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
        return redirect('board:board_detail', pk=pk)
    
    form = PostForm(instance=post)
    return HttpResponse(status=405)

def board_search(request):

    # 기본 context 초기화
    context = {
        'search_form': PostSearchForm(),
        'search_term': '',
        'object_list': None,
        'paginator': None,
        'page_obj': None,
    }
    
    search_term = request.GET.get('search_word', '')
    
    if request.method == "POST":
        search_form = PostSearchForm(request.POST)
        if search_form.is_valid():
            search_term = search_form.cleaned_data['search_word']
            post_list = Post.objects.filter(
                Q(post_title__icontains=search_term) | 
                Q(post_content__icontains=search_term)
            ).distinct()
        else:
            post_list = Post.objects.none()
            context.update({
                'search_form': search_form,
                'form_errors': search_form.errors
            })
    else:
        # GET 요청에서 검색어로 게시물 필터링
        if search_term:
            post_list = Post.objects.filter(
                Q(post_title__icontains=search_term) | 
                Q(post_content__icontains=search_term)
            ).distinct()
        else:
            post_list = Post.objects.none()
    
    # 페이지네이션
    paginator = Paginator(post_list, 12)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    # context 업데이트
    context.update({
        'search_term': search_term,
        'object_list': page_obj,
        'paginator': paginator,
        'page_obj': page_obj,
    })
        
    
    return render(request, 'board/board_search.html', context)



board/templates/board/board_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block extra-style %}
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<!-- Plugin -->
<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css" />
<script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>

<!-- ajax -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>


<!-- jQuery UI for Autocomplete -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<style>
    body {
    background: #fff;
    font-family: 'Roboto', sans-serif;
    }
    .container {
        background: #fff;
        padding: 0 20px;
    }
    .create-header {
        padding: 20px 0;
        display: flex;
        justify-content: space-between;
        align-items: center; /* 세로 중앙 정렬 */
    }
    .create-header h1 {
        margin: 0; /* margin 제거 */
        display: flex; /* Flexbox 컨테이너로 설정 */
        align-items: center; /* 세로 중앙 정렬 */
    }
    .img-container {
        position: relative;
        overflow: hidden;
        width: 100%; /* 원하는 고정 너비로 설정 */
        height: 600px; /* 원하는 고정 높이로 설정 */
        background-color: #000;
    }
    .img-container img {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        max-width: 100%;
        max-height: 100%;
        width: auto;
        height: auto;
    }
    .overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        align-items: flex-end;
    }
    .carousel-cap{
        width: 24px;
        margin: 20px 20px;
        border-radius: 24px;
        background-color: #373634;
        color: #fff;
    }
    
    .post-content {
        background-color: #fff; /* 흰색 배경 */
        padding: 20px; /* 내부 여백 */
        border: 1px solid #ddd; /* 테두리 */
        border-radius: 5px; /* 모서리 둥글게 */
        font-family: 'Arial', sans-serif; /* 글꼴 설정 */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 그림자 효과 */
    }

    .post-content h2 {
        font-size: 24px; /* 제목 크기 */
        margin-bottom: 10px; /* 아래 여백 */
        color: #333; /* 제목 색상 */
    }

    .post-content p {
        font-size: 14px; /* 본문 크기 */
        color: #666; /* 본문 색상 */
        margin-bottom: 10px; /* 아래 여백 */
    }

    .post-content li.h5 {
        font-size: 18px; /* 리스트 아이템 크기 */
        color: #333; /* 리스트 아이템 색상 */
        margin-bottom: 5px; /* 아래 여백 */
    }

    .post-content a {
        color: #007bff; /* 링크 색상 */
        text-decoration: none; /* 밑줄 제거 */
    }

    .post-content a:hover {
        text-decoration: underline; /* 링크에 호버 시 밑줄 추가 */
    }
    li{
        list-style: none;
    }

    form {
        display: flex;
        flex-direction: column;
    }

    label {
        margin-top: 10px;
    }

    input[type="text"],
    textarea {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: none; /* 테두리 제거 */
        border-radius: 5px; /* 둥근 모서리 */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 그림자 효과 */
        font-family: 'Arial', sans-serif; /* 글꼴 설정 */
        font-size: 16px; /* 글자 크기 */
    }

    textarea {
        height: 140px; /* 7줄 정도의 높이 */
        resize: none; /* 크기 조정 비활성화 */
    }

    input[type="text"]:focus,
    textarea:focus {
        outline: none; /* 포커스 시 아웃라인 제거 */
        box-shadow: 0 0 10px rgba(0, 123, 255, 0.5); /* 포커스 시 그림자 효과 */
    }
    .back {
        border: none;
    }
    .posting{
        border: none;

    }
    
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="create-header">
        <form action="{% url 'board:board_create' %}" method="post">
            {% csrf_token%}
            <button type="submit" class="btn btn-outline-secondary back"><i class="fa-solid fa-chevron-left"></i></button>
        </form>
        <h1>새 포스트 생성</h1>
        
        <button type="button" onclick="submitPostForm()" class="btn btn-outline-secondary posting">게시하기</button>

    </div>
    <div class="row">
        <div class="col-md-8 post-img" >
            <div id="carouselExampleControls" class="carousel slide">
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="img-container">
                        <!-- seed 뒤 포스트 id 부여 seed/{{post.id}} -->
                        <img src="https://picsum.photos/900/500/" class="img-fluid" alt="NO IMAGE">
                            <div class="overlay">
                                <!-- #373634 -->
                                <span class="carousel-cap"></span>
                            </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="img-container">
                        <img src="https://picsum.photos/900/500/" class="img-fluid" alt="NO IMAGE">
                            <div class="overlay">
                                <!-- #373634 -->
                                <span class="carousel-cap"></span>
                            </div>
                    </div>
                </div>
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>

        <ul class="col-md-4 post-content">
            <div style="display: flex; justify-content: space-between; margin-bottom: 12px;">
                <h5 class="mb-3"><i class="fa-solid fa-circle-user"></i>&nbsp;{{user}}</h5>
                <!-- <p>2024-07-09</p> -->
            </div>
            <form id="postForm" action="{% url 'board:form_submit' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <!-- 에러 메시지 표시 -->
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}
                                    <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                                {% endif %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <input type="hidden" name="uploadedFiles" id="uploadedFiles" value="">
            </form>
                
        </ul>
    </div>

</div>

<script>
    window.addEventListener('DOMContentLoaded', (event) => {
        var uploadedFiles = JSON.parse(sessionStorage.getItem('uploadedFiles') || '[]');
        console.log("Uploaded files:", uploadedFiles);  // 브라우저 콘솔에 출력
        if (uploadedFiles && uploadedFiles.length > 0) {
            // 이미지 표시 로직
            displayUploadedImages(uploadedFiles);
        } else {
            console.log("No uploaded files found");
        }
    });
    
    // 캐러셀 이미지 표시
    function displayUploadedImages(files) {
        var carouselInner = document.querySelector('.carousel-inner');
        carouselInner.innerHTML = '';  // 기존 내용 제거

        files.forEach((file, index) => {
            var carouselItem = document.createElement('div');
            carouselItem.className = 'carousel-item' + (index === 0 ? ' active' : '');
            
            var imgContainer = document.createElement('div');
            imgContainer.className = 'img-container';
            
            var img = document.createElement('img');
            img.src = file.dataUrl;
            img.className = 'img-fluid';
            img.alt = 'Uploaded image ' + (index + 1);
            
            var overlay = document.createElement('div');
            overlay.className = 'overlay';
            
            var carouselCap = document.createElement('span');
            carouselCap.className = 'carousel-cap';
            carouselCap.textContent = (index + 1) + '/' + files.length;
            
            overlay.appendChild(carouselCap);
            imgContainer.appendChild(img);
            imgContainer.appendChild(overlay);
            carouselItem.appendChild(imgContainer);
            carouselInner.appendChild(carouselItem);
        });
    }
    

    // 게시하기 폼 제출 시 폼 입력데이터 제출
    function submitPostForm() {
        var form = document.getElementById('postForm');
        // postForm 제출
        // postForm.submit();
        // formData 구성

        const formData = new FormData(form);
        console.log(formData)

        fetch("{% url 'board:form_submit' %}", {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: formData
        })
        .then(response => {
            if (!response.ok) {
                return response.text().then(text => { throw new Error(text) });
            }
            return response.json();
        })
        .then(data => {
                // 세션 갱신 후 리디렉션
                // res = response.json();
                // const post_Id = res.pk;
                const post_Id = data.pk;

                fetch("{% url 'board:refresh_session' %}")
                .then(() => {
                    // 브라우저 세션 삭제
                    sessionStorage.removeItem('uploadedFiles');

                      // board_detail 뷰로 리디렉션, pk 값 전달
                    const redirectUrl = `/board/detail/${post_Id}/`
                    window.location.href = redirectUrl

                });
            })
        .catch(error => {
            console.error(error);
            alert('오류가 발생했습니다. 다시 시도해 주세요. 오류 내용: ' + error.message);
        });
    }
                  
</script>
{% endblock %}

board/templates/board/board_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra-style %}
<link href="{% static 'css/board_list.css' %}" rel="stylesheet">
{% endblock %}
    
{% block content %}
<div class="my-container">
    <div class="head-container">
        <div class="direct-container">
            <p class="text-center">Community</p>
            <div class="row">
            <div class="d-flex justify-content-center">
                <!-- 검색 폼 -->
                <form id="search-form" action="{% url 'board:board_search' %}" method="post">
                    {% csrf_token %}
                    {{ search_form.search_word }}
                    <button id="search-button" type="submit">
                        <span class="material-symbols-outlined" style="font-size: 35px;">
                            search
                            </span>
                    </button>
                </form>
            </div>
            </div>
    </div>
</div>
<div class="container">
    <div class="stats" style="display: flex; justify-content: flex-end; margin: 20px 0px;">
        <form action="{% url 'board:board_create' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outlne-secondary registration" style="border: none;"><i class="fa-solid fa-pencil"></i></button>
        </form>
    </div>
    
    <div class="row">
        {% for post in posts %}
        <div class="col-6 col-md-4 col-lg-3 mb-3">
            <div class="img-container">
            <!-- seed 뒤 포스트 id 부여 seed/{{post.id}} -->
                <a id="click_a" href="{% url 'board:board_detail' post.pk %}">
                    {% if post.postimage_set.first %}
                    <img src="{{post.postimage_set.first.image_url.url}}" class="img-fluid" alt="random_img11">
                    {% else %}
                    <img src="https://picsum.photos/seed/{{post.id}}/300/300" class="img-fluid" alt="random_img11">
                    {% endif %}
                
                <div class="overlay">
                    <div class="top-row">
                        <span class="badge bg-light text-dark university-cap">
                            <i class="fa-solid fa-graduation-cap"></i>&nbsp;
                        </span>
                        <span class="badge bg-light text-dark visitors">
                            <i class="fa-solid fa-eye"></i>&nbsp;{{ post.visitors }}
                        </span>
                    </div>
                </div>
                </a>
            
            </div>
            <h4>{{ post.post_title }}</h4>
            <p><i class="fa-solid fa-circle-user" style="font-size: 1.2em; vertical-align: middle;"></i>&nbsp;{{ post.user }}</p>
        </div>
        {% empty %}
            <p class="text-center">게시물이 없습니다.</p>
        {% endfor %}

        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true"><i class="fa-solid fa-angles-left"></i></span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true"><i class="fa-solid fa-chevron-left"></i></span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link"><i class="fa-solid fa-angles-left"></i></span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link"><i class="fa-solid fa-chevron-left"></i></span>
                </li>
                {% endif %}
        
                {% with ''|center:page_obj.paginator.num_pages as range %}
                {% for _ in range %}
                    {% with forloop.counter as i %}
                        {% if i > page_obj.number|add:"-3" and i < page_obj.number|add:"3" %}
                            {% if i == page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">{{ i }}<span class="sr-only">(current)</span></span>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                            {% endif %}
                        {% endif %}
                    {% endwith %}
                {% endfor %}
                {% endwith %}
        
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true"><i class="fa-solid fa-angle-right"></i></span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true"><i class="fa-solid fa-angles-right"></i></span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link"><i class="fa-solid fa-angle-right"></i></span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link"><i class="fa-solid fa-angles-right"></i></span>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}