config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from config.views import HomeView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('roadmap/', include('roadmap.urls')),
    path('', HomeView.as_view(),name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/check/', views.check_profile, name='check_profile'),
    path('profile/create/step1/', views.profile_create_step1, name='profile_create_step1'),
    path('profile/create/step2/', views.profile_create_step2, name='profile_create_step2'),
    path('profile/create/step3/', views.profile_create_step3, name='profile_create_step3'),
    path('profile/create/step4/', views.profile_create_step4, name='profile_create_step4'),
    path('profile/complete/', views.profile_complete, name='profile_complete'),
    path('weekly_plan/', views.weekly_plan, name='weekly_plan'),
    path('api/get_nutrition/', views.get_nutrition, name='get_nutrition'),  # API 엔드포인트
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gallery with me</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bona+Nova+SC:ital,wght@0,400;0,700;1,400&family=Noto+Serif+KR:wght@200..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,400,0,0" />
  <script src="https://kit.fontawesome.com/a47086679e.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% block extra-style %}{% endblock %}
  <style>
    * {
        font-family: "Noto Serif KR", serif;
        font-optical-sizing: auto;
        font-weight: 300;
        font-style: normal;
    }
</style>
</head>

<body>
  {% block navbar %}
  <!-- 헤더 -->
  <div class="container-fluid mx-0 header fixed-top">
    <header class="d-flex flex-wrap justify-content-center py-2 container-fluid">
      <a href="/" class="d-flex align-items-center  mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <span class="logo fs-4">ENCH</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link" id="Sidebar-menu">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" class="bi bi-list" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
            </svg>
          </a></li>

        <li class="nav-item"><a href="#" class="nav-link" id="Sidebar-profile">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" class="bi bi-person-circle"
              viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
              <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1" />
            </svg>
          </a></li>
      </ul>
    </header>
  </div>
  <!-- 헤더end -->
  {% endblock %}

  <!-- 사이드바 -->
  <div class="sidebar sidebar-menu flex-shrink-0 p-3">
    <ul class="list-unstyled ps-0 mt-5">
      <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
          <a href="/user/weekly_plan" class="link-body-emphasis text-decoration-none">Plan</a>
        </button>
      </li>
      <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
          <a href="/board" class="link-body-emphasis text-decoration-none">Community</a>
        </button>
      </li>
      <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
          <a href="/roadmap/" class="link-body-emphasis text-decoration-none">Map</a>
        </button>
      </li>

      <li class="border-top "></li>
      <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
          <a href="#" class="link-body-emphasis text-decoration-none">Contact Us</a>
        </button>
      </li>
    </ul>
  </div>

  <div class="sidebar sidebar-profile flex-shrink-0 p-3">
    {% if user.is_authenticated %}
    <li class="mb-2">
        <form method="post" action="{% url 'user:logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn d-inline-flex align-items-center rounded border-0 "aria-expanded="false">LOGOUT</button>
        </form>
      </li>

    {% else %}
    <ul class="list-unstyled ps-0 mt-5">
        <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
            <a href="{% url 'user:login' %}" class="link-body-emphasis text-decoration-none">Login</a>
        </button>
        </li>
        <li class="mb-2">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed">
            <a href="{% url 'user:signup' %}" class="link-body-emphasis text-decoration-none">Register</a>
        </button>
        </li>
    </ul>
    {% endif %}
    </ul>
</div>

  {% block content %}{% endblock %}

  {% block footer %}
  <!-- footer -->
  <div class="container mt-4" style="border-top: 1px solid #dee2e6;">
    <footer class="pt-3 pb-3 mt-auto">
      <div class="mb-3">
        <p class="footer-text">ENCH</p>
        <p class="footer-text">상호: 엔치</p>
        <p class="footer-text">전자우편주소: admin@test.org</p>
        <p class="footer-text">© 2024 ENCH all rights reserved</p>
      </div>
    </footer>
  </div>
  <!-- footer end -->
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/base.js' %}"></script>
  {% block extra-js %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

<!-- {% block extra-style %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bona+Nova+SC:ital,wght@0,400;0,700;1,400&display=swap"
	rel="stylesheet">
{% endblock %} -->

{% block content %}
<!-- 메인화면 -->
<div id="MainCarousel" class="carousel slide" data-bs-ride="carousel">
	<div class="carousel-indicators">
		<button type="button" data-bs-target="#MainCarousel" data-bs-slide-to="0" class="active" aria-current="true"
			aria-label="Slide 1"></button>
		<button type="button" data-bs-target="#MainCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
	</div>
	<div class="carousel-inner">
		<div class="carousel-item active ">
			<img src="{% static 'sample_images/운동3(수정).jpg' %}" class="resized-image d-block w-100">
			<div class="carousel-caption d-none d-md-block ">
				<h3 class="carousel-title-description">함께 시작하는 건강 관리</h3>
				<h1 class="carousel-title">ENCH</h1>
				<p class="carousel-title-description" style="font-size: 25px; font-weight: 300;">건강 관리 플랫폼</p>
				<a href="/user/weekly_plan" class="btn btn-dark active carousel-btn" role="button">Plan으로 이동</a>
			</div>
		</div>
		<div class="carousel-item">
			<img src="{% static 'sample_images/운동4(수정).jpg' %}" class="resized-image d-block w-100">
			<div class="carousel-caption d-none d-md-block ">
				<h3 class="carousel-title-description">더 널리, 더 많은 사람들과 같이</h3>
				<h1 class="carousel-title">ENCH</h1>
				<a href="/exhibit" class="btn btn-dark active carousel-btn" role="button">Community로 이동</a>
			</div>
		</div>
	</div>
</div>
<!-- 메인화면end -->

<!-- 카테고리 -->
<div class="container-fluid">
	<div class="row">
		<div class="col-4 card card-cate p-0 border-0 rounded-0">
            <div class="ratio ratio-1x1">
                <a href="/user/weekly_plan">
                <img src="{% static 'sample_images/운동.jpg' %}" class="card-img rounded-0" alt="...">
                <div class="card-img-overlay d-flex flex-column justify-content-center text-center">
                    <h5 class="card-title">Plan</h5>
                </div>
                </a>
            </div>
		</div>
		<div class="col-4 card card-cate p-0 border-0 rounded-0">
            <div class="ratio ratio-1x1">
                <a href="/board">
                <img src="{% static 'sample_images/커뮤니티.jpg' %}" class="card-img rounded-0" alt="...">
                <div class="card-img-overlay d-flex flex-column justify-content-center text-center">
                    <h5 class="card-title">Community</h5>
                </div>
                </a>
            </div>
		</div>
		<div class="col-4 card card-cate p-0 border-0 rounded-0">
            <div class="ratio ratio-1x1">
                <a href="/roadmap/">
                <img src="{% static 'sample_images/나침반.jpg' %}" class="card-img rounded-0" alt="...">
                <div class="card-img-overlay d-flex flex-column justify-content-center text-center">
                    <h5 class="card-title">Road Map</h5>
                </div>
                </a>
            </div>
		</div>
	</div>
</div>
{% endblock %}